### ISSUE TITLE
Provide mechanism for custom directives to callback to an external object

### ISSUE THREAD

**Issue by blu-peter** [Intuity/prologue#3]
Custom directives may need to callback to an external object to register state. At the moment the only way to achieve this is to use a global variable, which makes it impossible to 'scope' callbacks from multiple invocations of the preprocessor.

**Comment by Intuity** [comment]
There is a new optional argument `callback` to the `evaluate` method, the value will be propagated to all directive instances (in-built and custom). This could be used to expose internal state from the preprocessor. In most cases the callback should only be used in a directive's `evaluate` routine, because this is the only point at which presence in the output file is confirmed.
